"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-04-25 17:12:36.411013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_applicants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legal_name', sa.String(length=256), nullable=False),
    sa.Column('trading_name', sa.String(length=256), nullable=True),
    sa.Column('registration_number', sa.String(length=128), nullable=False),
    sa.Column('country_of_incorporation', sa.String(length=8), nullable=False),
    sa.Column('incorporation_date', sa.Date(), nullable=True),
    sa.Column('business_type', sa.String(length=128), nullable=True),
    sa.Column('regulated', sa.Boolean(), nullable=False),
    sa.Column('regulator', sa.String(length=128), nullable=True),
    sa.Column('lei_code', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('ubo_complete', sa.Boolean(), nullable=False),
    sa.Column('addr_line1', sa.String(length=256), nullable=False),
    sa.Column('addr_line2', sa.String(length=256), nullable=True),
    sa.Column('addr_city', sa.String(length=128), nullable=False),
    sa.Column('addr_state', sa.String(length=128), nullable=True),
    sa.Column('addr_postal_code', sa.String(length=32), nullable=False),
    sa.Column('addr_country_code', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individual_applicants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=8), nullable=False),
    sa.Column('country_of_residence', sa.String(length=8), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('investor_class', sa.Enum('RETAIL', 'PROFESSIONAL', 'ELIGIBLE_COUNTERPARTY', 'INSTITUTIONAL', name='investorclass'), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('is_sanctioned', sa.Boolean(), nullable=False),
    sa.Column('tax_id', sa.String(length=64), nullable=True),
    sa.Column('source_of_funds', sa.String(length=256), nullable=True),
    sa.Column('addr_line1', sa.String(length=256), nullable=True),
    sa.Column('addr_line2', sa.String(length=256), nullable=True),
    sa.Column('addr_city', sa.String(length=128), nullable=True),
    sa.Column('addr_state', sa.String(length=128), nullable=True),
    sa.Column('addr_postal_code', sa.String(length=32), nullable=True),
    sa.Column('addr_country_code', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_type', sa.Enum('INDIVIDUAL', 'CORPORATE', 'INSTITUTIONAL', name='casetype'), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('fund_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'DOCUMENTS_PENDING', 'IN_REVIEW', 'PENDING_INFO', 'APPROVED', 'REJECTED', 'EXPIRED', name='casestatus'), nullable=False),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='risktier'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewer_id', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1024), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('case_metadata', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('applicant_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.Enum('PASSPORT', 'NATIONAL_ID', 'DRIVING_LICENCE', 'PROOF_OF_ADDRESS', 'BANK_STATEMENT', 'UTILITY_BILL', 'CERTIFICATE_OF_INCORPORATION', 'ARTICLES_OF_ASSOCIATION', 'SHAREHOLDER_REGISTER', 'AUDITED_ACCOUNTS', 'BOARD_RESOLUTION', 'PROOF_OF_AUTHORITY', 'SOURCE_OF_FUNDS', 'TAX_CERTIFICATE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('storage_ref', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', 'EXPIRED', name='documentstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1024), nullable=True),
    sa.Column('country_of_issue', sa.String(length=8), nullable=True),
    sa.Column('document_number', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['kyc_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('kyc_cases')
    op.drop_table('individual_applicants')
    op.drop_table('corporate_applicants')
    # ### end Alembic commands ###
